Controllers films users
M0L0D0Y/java-filmorate pull request #1
Opened 2022-05-29 08:07 UTC by M0L0D0Y

2022-05-29 19:47 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RestController
код легче читать, когда аннотации расположены в порядке от самой короткой к длинной

2022-05-29 19:48 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Long, Film> listFilms = new HashMap<>();
тип должен быть Map

2022-05-29 19:49 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final int LINE_LENGTH = 201;
константы должны быть перед другими полями

2022-05-29 19:52 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if ((film.getName() == null)||(film.getName().equals(""))) {
валидацию лучше вынести в отдельный приватный метод и вызывать тут этот метод

также нужно расставить правильно пробелы и убрать лишние скобки
и пустую строку вынести в константу, и вызывать у нее equals, потому что возвращенное из метода значение может быть null
```
        if (film.getName() == null || EMPTY_STRING.equals(film.getName())) {
```

2022-05-29 19:53 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Продолжительность фильма меньше нуля");
стоит добавить значение в сообщение исключения

2022-05-29 19:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
у всех классов страдает форматирование, нужно сделать автоформат CTRL ALT L в идее

2022-05-29 19:55 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +
тест стоит доделать

2022-05-29 19:56 UTC, makholin requested changes
Нужно исправить замечания

2022-05-29 23:16 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RestController
исправил

2022-05-29 23:16 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Long, Film> listFilms = new HashMap<>();
исправил в обоих контроллерах

2022-05-29 23:16 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final int LINE_LENGTH = 201;
вынес все константы

2022-05-29 23:17 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if ((film.getName() == null)||(film.getName().equals(""))) {
исправил это замечание

2022-05-29 23:17 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Продолжительность фильма меньше нуля");
добавил

2022-05-29 23:18 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
сделал на всех классах

2022-05-29 23:18 UTC, M0L0D0Y commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +
написал тесты для валидаторов

2022-05-30 21:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final String DOG_SYMBOL = "@";
it's not dog symbol))

`EMAIL_SYMBOL` is ok

2022-05-30 21:39 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Нет названия фильма");
в сообщения исключений стоит добавить значения, которые оказались невалидными, проще отлаживать будет после падений

2022-05-30 21:43 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    private static Validator validator;
тестирование валидатора лучше делать в `ValidatorTest`
это актуально для всех сервисов

ПС у многих ребят spring boot test оставлен пустым, я не нашел в тз упоминания об этом, поэтому обсудите с наставником этот тест и можете либо пустым оставлять, либо с реализацией, либо вообще не делать его

2022-05-30 21:44 UTC, makholin requested changes
Нужно исправить замечания

2022-05-30 21:48 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final String DOG_SYMBOL = "@";
исправил

2022-05-30 21:50 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Нет названия фильма");
сделал

2022-05-30 21:55 UTC, M0L0D0Y commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    private static Validator validator;
сделал тестирование в ValidationTest.

ПС в тз было требование сделать тесты для валидатора, но я не знал как, пока не сказал что их нужно делать. В группе так же ребята интересовались по поводу тестов. Может другие ревьюеры у них, но многие писали тесты.

2022-05-31 21:46 UTC, makholin approved these changes

2022-05-31 22:38 UTC, merged