Add friends likes
M0L0D0Y/java-filmorate pull request #2
Opened 2022-06-13 14:37 UTC by M0L0D0Y

2022-06-13 22:52 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
пустая строка после аннотаций не нужна

2022-06-13 22:53 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage memoryFilmStorage;
в названии поля не нужно указывать конкретную реализацию интерфейса, которая будет подставлена в поле

это всегда может измениться и название станет неактуальным, лучше просто filmStorage

2022-06-13 22:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends Exception {
такие исключения лучше делать наследниками RuntimeException

2022-06-13 22:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> listFriends = new HashSet<>();
это поле лучше сделать последним в списке полей, оно не самое важное

2022-06-13 22:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int likes;
отдельное поле для количества лайков не нужно
можно у списка лайкнувших людей вызывать size()

2022-06-13 22:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> idUsersWhoLiked = new HashSet<>();
можно назвать проще `likedUsers`

2022-06-13 22:57 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Validator.java
> +
достаточно одной пустой строки

2022-06-13 22:58 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> UsersWhoLiked;
переменные должны быть с маленькой буквы

2022-06-13 22:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
пустая строка после тела метода не нужна

2022-06-13 23:02 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Autowired
поля и методы нужно разделять пустой строкой

2022-06-13 23:03 UTC, makholin requested changes
Нужно исправить замечания и исправить пулл реквест, чтобы он содержал только новые изменения

2022-06-14 07:36 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
исправил

2022-06-14 07:38 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage memoryFilmStorage;
исправил на сколько понял

2022-06-14 07:38 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends Exception {
исправил

2022-06-14 07:39 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> listFriends = new HashSet<>();
исправил

2022-06-14 07:39 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/Validator.java
> +
исправил

2022-06-14 07:43 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> UsersWhoLiked;
исправил

2022-06-14 07:44 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
исправил

2022-06-14 07:45 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Autowired
исправил

2022-06-14 07:46 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> idUsersWhoLiked = new HashSet<>();
исправил

2022-06-14 07:46 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int likes;
исправил

2022-06-14 22:47 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> listFriends = new HashSet<>();
лучше friends или friendsList

2022-06-14 22:47 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> usersWhoLiked;
можно сразу присвоить значение при объявлении переменной

2022-06-14 22:50 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmList.sort(Comparator.comparingInt(o -> o.getLikedUsers().size() * (-1)));//reversed() почему-то не работает
возможно, потому что sort сортирует исходный массив внутри себя, а reversed возвращает новый измененный массив и тогда надо делать так
`list = list.reversed()`

2022-06-14 22:52 UTC, makholin approved these changes
Работа принята

Незначительные замечания можно пофиксить в ветке, запушить ее и замержить этот пулл реквест

2022-06-15 19:28 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> listFriends = new HashSet<>();
исправил

2022-06-15 19:29 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> usersWhoLiked;
исправил

2022-06-15 19:31 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmList.sort(Comparator.comparingInt(o -> o.getLikedUsers().size() * (-1)));//reversed() почему-то не работает
пробовал, не получается. оставил как есть

2022-06-15 19:32 UTC, merged