Add database
M0L0D0Y/java-filmorate pull request #3
Opened 2022-07-08 15:16 UTC by M0L0D0Y

2022-07-10 17:26 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +//TODO доделать сервис для фильмов и юзеров
нужно доделать или убрать коммент

2022-07-10 17:27 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Genre getGenreById(@PathVariable int id) throws NotFoundException {
NotFoundException стоит сделать рантайм исключением и убрать его из сигнатур методов

2022-07-10 17:28 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //@NotEmpty(message = "Нет рейтинга")
закоментированный код нужно удалить

2022-07-10 17:29 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private int statusId;
можно подумать над тем, чтобы не использовать отдельную таблицу со значениями статуса дружбы, а использовать обычный enum и сохранять это значение как varchar в отдельную колонку

2022-07-10 17:31 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Logger log = LoggerFactory.getLogger(FilmDbStorage.class);
можно использовать аннотацию @Sl4j от ломбока, он сам создаст log

2022-07-10 17:33 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final JdbcTemplate jdbcTemplate;
уровень бизнес логики ничего не должен знать о хранении данных
для этого есть уровень DAO

другими словами сервисы для хранения данных должны только вызывать стораджи, а вот внутри стораджей уже реализуется логика для хранения  в определенном хранилище

2022-07-10 17:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        jdbcTemplate.update(query, filmId, userId);
данные тут должен обновлять filmStorage.addLike()

во всех остальных методах сервиса тоже нужно перенести логику работы с бд в сторадж

2022-07-10 17:37 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static final int NO_STATUS = 0;
стоит вынести эти значения в enum

2022-07-10 17:39 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private int getStatusIdFriendUser(long userId, long friendId) {
лучше назвать getFriendshipStatus

2022-07-10 17:40 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        jdbcTemplate.update(queryConfirmFriendshipFriend, 2, friendId, userId);
непонятно, что означает цифра 2, нужно либо вынести в константу либо использовать енум

2022-07-10 17:42 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
лучше назвать DatabaseFilmStorage, чтобы было единообразно с FilmStorage и InMemoryFilmStorage
название бина в аннотации компонента лучше назвать так же, как класс

2022-07-10 17:43 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Film addFilm(Film film) throws ValidationException {
ValidationException тоже стоит сделать рантайм исключением и убрать из сигнатур методов

2022-07-10 17:45 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        log.info("Рейтинг для фильма с id {} получен", film.getId());
такой лог будет информативнее:
`log.info("Фильм {} имеет рейтинг {}", film.getId(), rating.getName())`

2022-07-10 17:47 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        log.info("Значения в таблицу FILM_RATING внесены");
такой лог не даст никакой информации о произведенных действиях, даже будет не понятно, из какого именно метода он выведен

для jdbcTemplate можно настроить логирование так, чтобы в лог выводились все запросы с параметрами
стоит попробовать так сделать (только уровень debug лучше поставить)

2022-07-10 17:48 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Component("InMemoryFilm")
лучше назвать также как класс

2022-07-10 17:49 UTC, makholin commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
нужно удалить

2022-07-10 17:51 UTC, makholin requested changes
Нужно исправить замечания

2022-07-11 07:53 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +//TODO доделать сервис для фильмов и юзеров
убрал

2022-07-11 07:54 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //@NotEmpty(message = "Нет рейтинга")
исправил

2022-07-11 07:59 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        log.info("Рейтинг для фильма с id {} получен", film.getId());
исправил

2022-07-11 07:59 UTC, M0L0D0Y commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
удалил

2022-07-11 08:08 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Film addFilm(Film film) throws ValidationException {
не совсем понимаю как реализовать это. вопрос в slake

2022-07-11 08:20 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private int statusId;
исправил

2022-07-11 09:49 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Genre getGenreById(@PathVariable int id) throws NotFoundException {
исправил

2022-07-11 12:07 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private int getStatusIdFriendUser(long userId, long friendId) {
исправил

2022-07-11 12:07 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        jdbcTemplate.update(queryConfirmFriendshipFriend, 2, friendId, userId);
исправил

2022-07-11 12:10 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
исправил

2022-07-11 12:11 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Film addFilm(Film film) throws ValidationException {
исправил

2022-07-11 12:13 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        log.info("Рейтинг для фильма с id {} получен", film.getId());
исправил

2022-07-11 12:14 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static final int NO_STATUS = 0;
исправил

2022-07-11 12:23 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Logger log = LoggerFactory.getLogger(FilmDbStorage.class);
исправил

2022-07-11 12:24 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        log.info("Значения в таблицу FILM_RATING внесены");
исправил

2022-07-11 12:24 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Component("InMemoryFilm")
исправил

2022-07-11 15:07 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final JdbcTemplate jdbcTemplate;
переделал

2022-07-11 15:07 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        jdbcTemplate.update(query, filmId, userId);
переделал

2022-07-11 20:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private StatusFriendship status;
нужно поменять порядок слов в имени, потому что последнее слово в классе обычно описывает сущность

раз это статус дружбы, то будет правильно `FriendshipStatus`

2022-07-11 20:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final DatabaseFriendshipStorage friendshipStorage;
тут должен быть такой же подход, как с коллекциями - тип должен быть интерфейсом `FriendshipStorage friendshipStorage`
 а правильная реализация спрингом должна подставляться с помощью @Qualifier

2022-07-11 20:15 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private StatusFriendship status;
исправил

2022-07-11 20:16 UTC, makholin requested changes
Нужно исправить пару замечаний

2022-07-11 20:18 UTC, M0L0D0Y commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final DatabaseFriendshipStorage friendshipStorage;
исправил, не добавлял  @Qalifier, реализация интерфейса пока только одна

2022-07-11 21:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/PopularFilmsStorage.java
> +public interface PopularFilmsStorage {
для фильмов можно сделать один сторадж для всего

если хочешь логику лайков держать отдельно, то можно сделать отдельный сервис для этого, но хранилище лучше не разделять, оно должно быть одно для всей работы по хранению фильмов

но и твое решение имеет место быть, особенно если система будет развиваться и каждый дао интерфейс будет расширяться
тогда этот сторадж можно было бы назвать LikeStorage

2022-07-11 21:11 UTC, makholin approved these changes
Работа принята

2022-07-12 10:18 UTC, merged